### PR TITLE
Bump versions and move to GitHub actions

### PR DESCRIPTION
**Pull request by flaeppe**
* Remove testing with Django<2.2 and Python<3.7

  Newer versions of mypy also (incorrectly) don't accept overriding enum
  attributes when subclassing. Mitigated by temporarily removing
  attributes from Enum base class.
  
  Mypy ticket can be found here: https://github.com/python/mypy/issues/12132

* Move to GitHub actions

---

Based on https://github.com/5monkeys/django-enumfield/pull/66#issuecomment-1003998396

I also tried including `Django==3.2` but it failed, felt more reasonable to bump that in a separate PR.

### CODE REVIEW

**Comment by flaeppe** [comment]
Not sure, but could there be some configuration needed to trigger actions to run? It worked fine in my fork (without having to configure anything): https://github.com/flaeppe/django-enumfield/actions/runs/1801846479

**Comment by Swamii** [comment]
@flaeppe The actions doesn't seem to run when added from outside. For djedi-cms we merged the PR to another branch, opened a pr to master, ran the actions (which didn't even run immediately), and _then_ merged it.

The move to `getattr` for the dunder properties seems fine. Is this mergable?

**Comment by flaeppe** [comment]
@Swamii Since `mypy>=0.940` support for overriding dunder attributes is resolved. If we can run with that mypy version, I'd suggest we reverse the `getattr`-approach

**Comment by Swamii** [comment]
> @Swamii Since `mypy>=0.940` support for overriding dunder attributes is resolved. If we can run with that mypy version, I'd suggest we reverse the `getattr`-approach

Let's do that then 👍

**Comment by flaeppe** [comment]
@Swamii I've bumped the changes now. Think it's mergable, too bad with CI though. Not sure why it won't trigger. Perhaps since all github action files are new?

**Comment by Swamii** [comment]
Great let's just merge it. But last thing: changelog entry for these changes

**Pull request merged**
