### PR TITLE
classproperty has been moved to django.utils.functional

### PR DESCRIPTION
**Pull request by lamby**
re. #62

### CODE REVIEW

**Comment by lamby** [comment]
With the release of 3.1, it would be great if this was merged.

**Comment by jturmel** [comment]
Two things:
* This breaks Django older than 3.1
* You need to add Django 3.1 to test config

**Comment by lamby** [comment]
Thanks for the quick review. Updated. :+1:

**Comment by jturmel** [comment]
You're still failing, you can see the results in Travis at the link below, you should run the tests locally before pushing up.

**Comment by lamby** [comment]
Sorry for the noise. I can't seem to get mypy working locally, but I've just pushed another update that I think should fix it.. will check after the tests have run. :+1:

**Comment by lamby** [comment]
The tests are still failing, but it looks like this is due to unrelated reasons:

```
django_enumfield/enum.py:118: error: Missing return statement
```

(I do not touch this line.)

**Comment by lamby** [comment]
Any ideas? :)

**Comment by ca-simone-chiorazzo** [comment]
Any news on this? We are stuck updating to Django 3 due to this problem.

**Comment by lamby** [comment]
Alas, I am still stuck with this seemingly-unrelated test issue. :)

**Comment by hannseman** [comment]
Thanks for your PR and sorry for the late review! The CI failures you where seeing was totally unrelated to your PR. The issue was that mypy and black have been updated since we last ran CI and in these newer versions some new rules was added which caused failures. I took the liberty to fix these issues directly in this PR. We'll release a new version on PyPI ASAP!

**Comment by lamby** [comment]
Yay!

**Comment by jturmel** [comment]
Great!

**Comment by lundberg** [comment]
Version `2.0.2` released.

**Pull request merged**
