### PR TITLE
#15 Use enum34 class

### PR DESCRIPTION
**Pull request by fcurella**
Ref #15

Most tests are passing, but I had to drop some existing features:
- The value of the field is an `Enum`, therefore `self.assertTrue(isinstance(person.status, int))` fails
- The custom `Enum.label()` _method_ conflicts with the members' `label` _property_, so I had to pick one. I've picked the `property`

### CODE REVIEW

**Comment by hannseman** [comment]
Wow! Thank you. So sorry for the late response, I've been on a vacation. Will have a look at this tomorrow.

**Comment by andreif** [comment]
@fcurella I have created PR fcurella/django-enumfield#1 to fix issues with labels and migrations. Please have a look

**Comment by fcurella** [comment]
Thanks @andreif,

I'm out for the weekend, I'll take a look on Monday

**Comment by fcurella** [comment]
@andreif the changes are simple enough, I've just merged your PR.

Thanks again :)

**Comment by andreif** [comment]
:+1: 

There are still some issues, which I will hopefully look at during the weekend or on Monday.

**Comment by andreif** [comment]
@fcurella I've made some changes in fcurella/django-enumfield#2 but they may be somewhat controversial. There is still an unresolved issue with inconsistent field value.

**Comment by andreif** [comment]
Hey @fcurella, please have a look at fcurella#3

**Comment by jleclanche** [comment]
For those looking for a simple solution to use IntEnum in choices and validate against it automatically:

https://gist.github.com/jleclanche/fbaefb66ef5600191679e17b1956e1e4

**Comment by listingmirror** [comment]
Has this been tested with Django 1.10?  Seems like this would be a good time to make it work and merge.

Hitting a 1.10 bug with 1.3b2 but have not had time to reproduce it yet...

**Comment by nathando** [comment]
Hi, is there any update on this. I just updated to 1.11 and seem like non of the EnumField update itself anymore, even if we call 'save' on the model ?

**Comment by kjagiello** [comment]
@nathando I've just tested this branch against Django 1.11 and all of the tests have passed. Do you have a test case reproducing the problem you are experiencing?

**Comment by nathando** [comment]
@kjagiello Hi, i've found out that it is this issue https://github.com/5monkeys/django-enumfield/issues/39 and currently apply the hot fix which was posted there. The problem is Django 1.10+ consider enumfields deferred.

**Comment by kjagiello** [comment]
@nathando Oh, I see. I've just produced a quick bugfix for that issue. Check out #42

**Comment by nathando** [comment]
@kjagiello thank you! Hope some one review and merge it soon to release. Otherwise, other ppl will hit the same issue.

**Comment by nkprince007** [comment]
Hope someone reviews this pull request soon and merges it for native `Enum` support.

**Comment by bh** [comment]
Works fine for Django 1.11.15. Thanks a lot.

**Comment by superduper** [comment]
Hey! 
Any help needed on this PR? What's left to do in order to merge it?

**Pull request merged**
